title: MUDE Workbook 2025
author: MUDE Teachers and the Student Army from Delft University of Technology, built with <a href="https://teachbooks.io">TeachBooks</a> and <a href="https://jupyterbook.org/">Jupyter Book</a>, <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="license noopener noreferrer"">CC BY 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg" alt=""></a> #add your own name here

execute:
  execute_notebooks: "off"

only_build_toc_files: true

html:
  baseurl :  "https://mude.citg.tudelft.nl/workbook-2025"

sphinx:
  config:
    html_theme_options:
      logo:
        text: Workbook 2025
        image_light: MUDE_Logo-small.png
        image_dark: MUDE_Logo-small.png
      repository_url: "https://github.com/TUDelft-MUDE/workbook-2025"
      path_to_docs: "book"
      repository_branch: "draft"
      use_repository_button: true
      use_issues_button : true
# START REMOVE-FROM-PUBLISH
      announcement: "<p>This book is under construction. The version currently shared with students: <a href='https://mude.citg.tudelft.nl/workbook-2025' style='color: cyan;'>mude.citg.tudelft.nl/workbook-2025</a></p>"
# END REMOVE-FROM-PUBLISH
    html_show_copyright: false
    html_last_updated_fmt: '%B %-d, %Y'
    html_static_path: ["figures"] # add folders that contain files that need to be included, such as the location of the logo(s)
    mathjax3_config:
      chtml: {
        mtextInheritFont: true # To typeset text within math prettier
      }
    tud_change_logo: false
    named_colors_custom_colors: {'attributiongrey':[150,150,150]}
  extra_extensions:
    - sphinx.ext.imgconverter
    - jupyterbook_patches
    - download_link_replacer
    - sphinx.ext.extlinks
    - sphinx_image_inverter
    - sphinx_exercise
    - teachbooks_sphinx_tippy
    - sphinx_tudelft_theme
    - sphinx_accessibility

teachbooks:
  attribution_color: attributiongrey
  attribution_location: margin

bibtex_bibfiles: 
  - references.bib
